### ISSUE TITLE
Minigrace error message for indenting issues

### ISSUE THREAD

**Issue by KimBruce** [gracelang/minigrace#150] opened 2015-09-05 19:32 UTC
My students are running into the following issue a lot (it's the first week of classes!)
![graceerror](https://cloud.githubusercontent.com/assets/1810938/9700900/defd2608-53c9-11e5-986c-145fce770d83.png)

The problem of course is that they are indenting improperly.  It would be very helpful if the error message was amended to suggest that it is likely a problem with indenting rather than leaving out ().

Kim

**Comment by apblack** [comment] 2015-09-07 15:58
It took me a long time to see the issue.  The parser is happy until it sees the "." after "text", and then it thinks that the method being requested is graphicApplication.size (400,400) text, and that the final part of the name is not followed by an argument list.

I'm guessing that we could produce a message that says something like 

    method request graphicApplication.size (400,400) text must end with an argument list

Would that help?

**Comment by KimBruce** [comment] 2015-09-07 20:53
The actual problem is that the student had a problem with indenting.  Here is another simpler example:
```
print "hello"
 print (5)
```
The error message is:
```
Syntax error: Unknown method 'print()print'. This may be a spelling mistake or an attempt to access a method in another scope.
    in "testindent" (line 1, column 1)
```
The actual problem is that the second print is indented one space too far.  Thus the system is interpreting the problem as there is no legal method request print "hello" print (5).  That is correct, but not helpful.  What I'm hoping for is another line in the error message saying that this error often occurs when the following line is indented more than the line listed.

(I've already had to explain this to students twice this afternoon -- we're in lab now, and several times on Friday.)

**Comment by apblack** [comment] 2017-02-03 15:35
Perhaps every syntax error could check for being on a continuation line, and ask if that was intended?

**Comment by KimBruce** [comment] 2017-02-03 17:17
Perhaps a bit of an overkill.  I'm suggesting that if the error is an "unknown method" and it comes as part of a continuation line then ask if that was intended.  It happened a lot to my students at the beginning.

**Comment by apblack** [comment] 2017-02-03 21:52
If you look at the original issue, you will see that the problem is not "unknown method", but "a multi-part method request must end with ...".  I'm guessing that just about any parse error can be caused by splicing lines together accidentally.  Still, I'll try patching these two specific messages, and you can tell me how you like it.

**Comment by apblack** [comment] 2017-02-06 19:30
I've augmented the error reporting for "a multi-part method request must end with ...", and for any error that is reported as originating from a range that spans multiple lines.  In both of these cases, the compiler now asks if the programmer intended to continue the line.

For example:

![image](https://cloud.githubusercontent.com/assets/410893/22662848/4e1d9250-ec5f-11e6-80d5-5fb6c47041eb.png)

and

![screen shot 2017-02-06 at 11 28 53](https://cloud.githubusercontent.com/assets/410893/22662906/8c787e48-ec5f-11e6-9482-5cf4b4764e3c.png)

I'm going to close this now.  It can be reopened if this solution does not prove satisfactory.

**Closed by apblack** 2017-02-06 19:30 UTC

**Comment by KimBruce** [comment] 2017-02-06 20:17
I like the fix.  However the version I downloaded has a slightly different text:  

The indentation tells me that this is a continuation of the previous line; is that what you intended?

The “me” feels a bit odd.

Kim

**Comment by apblack** [comment] 2017-02-06 22:43
Yes, I agree.  That's why I changed it to the current, less anthropomorphic, text.  (I was trying this on a branch, which was why you didn't get it when you pulled "master".)
