### ISSUE TITLE
JS Runtime crashes when trying to index a lazy sequence

### ISSUE THREAD

**Issue by reid47** [gracelang/minigrace#97] opened 2015-05-27 22:32 UTC
When you try to perform integer addition or multiplication elements of a list of strings to an integer within a while block, or a for loop, or some similar structure, you get the runtime error "Internal error around line [#] of [file name]: TypeError: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined".

    var dict:Dictionary<String,Number> := dictionary.with("hello" :: 4, "apple" :: 47, "world" :: 19)
    def keys = dict.keys
    var sum := 0

    for(1..(keys.size)) do { i->
        sum := sum + keys[i]
    }

In this case, the error directs you to the beginning of the `for` loop, but the error is actually caused by the line within the for loop. In a block with many lines of code, this makes debugging difficult.

**Comment by apblack** [comment] 2015-05-28 16:02
The error is not from trying to add string to integers (which gives NaN — perhaps not the right thing, but that's what it does right now.)   

You get the same error if you change dict.keys to dict.values.  I don't yet understand the cause.  The error message says that there is a but in the JavaScript runtime, and that the thing that we are `call`ing (which should be a function) is undefined.

**Comment by apblack** [comment] 2015-06-11 19:44
It turns out that the JS code generator was special-casing the ```[]``` operator incorrectly, by-passing the
normal checks for method existence.  This is fixed in commit 7848459ba7377ef7cd48bce527def219c3751109

**Closed by apblack** 2015-06-11 19:44 UTC
