### ISSUE TITLE
Lists and Exception

### ISSUE THREAD

**Issue by KimBruce** [gracelang/minigrace#132] opened 2015-07-31 21:32 UTC
Lists do not raise exceptions where I might have expected.  Look at the following code
```
def lst = list.with(2,4,6)
def n = "sdf".asNumber
print("n = {n}")
lst.at(n)put(12)
print(lst)
def s = lst.at(n)
print(s)
```

This results in output:
```
n = NaN
[2, 4, 6]
12
```

I would have expected this to throw an exception at lst.at(n)put(12) as the value of n is NaN, which is not a legal index.  However, no error resulted and when the list was printed there was no sign of the 12.  However, when we accessed lst.at(n), the 12 is indeed there.

Looking at the code for list, it appears there is an attempt to check for legal subscripts, but it clearly does not work for this case.  My own preference is to eagerly throw an exception when NaN arises, but even if we delay, it should raise an exception when used as an index.

**Comment by apblack** [comment] 2015-07-31 23:23
You are running this on the JS backend, right?  I think that the issue is that NaN answers false when compared to anything.  Look at this (from Safari's Javascript console):

```
> a = new Array
< []
> a[3] = 6
< 6
> a
< [undefined × 3, 6]
> w = NaN
< NaN
> w === w
< false
> w > 10
< false
> w < 10
< false
> a[w] = 12
< 12
> a
< [undefined × 3, 6]
> a[w]
< 12
```
So it might be possible to fix this problem by inverting the direction of the tests.  So, if the bounds of the (underlying) Javascript array are 0..12, we could ask
```
> 12 >= w
< false
> 0 <= w
< false
```
rather that `w <=12` and `w>= 0`.

That would be a small fix, and one that would not slow down lists any more than they are already.

**Comment by kjx** [comment] 2015-08-01 00:45
> On 1/08/2015, at 9:32am, Kim Bruce <notifications@github.com> wrote:
> 
> def n = "sdf”.asNumber

isn’t this the problem? 
Why should this return a NaN rather than throwing an exception immediately?

More to the point, generally don’t we assume “x.asY” is total - 
so e.g. aNumber.asString makes some kind of sense (any number can be converted into a string)
but I’’m not sure aString.asNumber does…

James

**Comment by KimBruce** [comment] 2015-08-01 01:18
Yes, all of this came up as I'm writing the exceptions chapter and
discovering that things that I expected to throw exceptions did not. So I'd
be happy having "sdf".asNumber to throw an exception.

By the way, in terms of tests, the only way I found to check for "NaN" is
to try something like (possiblyBad.asString == "NaN")

**Comment by apblack** [comment] 2015-08-01 05:01
The BasicTypes document is clear about what "foobar".asNumber does.  We can change it if you like, but it might be a bad idea, if you think about the consequences.  Perhaps you want to open another issue for this?

So long as we use IEEE floating point, then we have NaN as a possible number.  Kim's original point was that indexing an array by NaN should be an exception.  I agree 100% with that.

**Comment by apblack** [comment] 2015-08-04 06:13
This is now fixed in the pdx ~grace IDE.  The changes will be committed to the master branch shortly.
The output from your program is
```
n = NaN
BoundsError at line 645 of collectionsPrelude: index NaN out of bounds 1..3
  called from Exception.raise at line 645 of collectionsPrelude
  called from object.at()put at line 4 of issue132
  called from execution environment
 
644:                     mods := mods + 1
 
645:                     native "js" code ‹var  ix = var_n._value;
 
646:                             if (!(ix >= 1) || !(ix <= this.data.jsArray.length + 1)) {
Stack frames:
  issue132 module
    lst
 = [2, 4, 6]
    n
 = NaN
```

**Closed by apblack** 2015-08-04 06:13 UTC
